import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import HeaderBar from '@/app/components/HeaderBar';
import Footer from '@/app/components/Footer';
import ThemeRegistry from '@/app/components/ThemeRegistry';
import { defaultLocale } from '@/middleware';
import { getDictionary, localeType } from '@dictionaries';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dentons Taiwan | 大成台灣律師事務所',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params: { lang },
}: {
	children: React.ReactNode;
	params: { lang: localeType };
}) {
	const dict = await getDictionary(lang);

	return (
		<html lang={lang ?? defaultLocale}>
			<body className={inter.className}>
				<ThemeRegistry options={{ key: 'mui' }}>
					<HeaderBar dict={dict} />
					{children}
					<Footer />
				</ThemeRegistry>
			</body>
		</html>
	);
}
